### ISSUE TITLE
Rake Error

### ISSUE THREAD

**Issue by JennTurnr** [alexch/learn_ruby#12]
Good Evening,

I have been unable to run the tests and I have no clue what is wrong. I am encountering an issue in the terminal after running the 'rake' command per the instructions in the index.html file. This is the message that I receive, any suggestions or advice would be greatly appreciated. Thank you. 

$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/usr/local/rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in`<main>'
(See full trace by running task with --trace)

$ rake --trace
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/application.rb:632:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/application.rb:94:in`block in load_rakefile'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/application.rb:93:in`load_rakefile'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/application.rb:77:in `block in run'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/application.rb:165:in`standard_exception_handling'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/bin/rake:33:in`<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p392/bin/rake:19:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p392/bin/rake:19:in`<main>'
/usr/local/rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in`<main>'

**Comment by imurchie** [comment]
Hi! Sorry to hear you're having problems.

Where are you running "rake"? You should be inside one of the numbered directories (e.g., learn_ruby/00_hello/) when running it.

So:

> cd learn_ruby/00_hello
> rake

Ought to work (your fork of the repository has the Rakefile in it, I can see).

Best,
Isaac.

**Comment by JennTurnr** [comment]
Hi thanks for getting back to me, I'm running rake under those directories
but no change, I tried uninstalling and reinstalling rvm, also changed
permissions, nothing is working and I don't know how to fix. Here's what I
get now:

Last login: Thu Aug  8 09:31:08 on console
-bash: __rvm_add_to_path: command not found (**THIS NOW SHOWS WHEN I OPEN A
NEW SHELL WINDOW)

$ gem install rspec
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/config_file.rb:221:in
`read': Is a directory - /Users/lindaturner/.gemrc (Errno::EISDIR)
from
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/config_file.rb:221:in
`load_file'
from
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/config_file.rb:168:in
`initialize'
from
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:384:in
`new'
from
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:384:in
`configuration'
from
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:634:in
`path'
from
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/source_index.rb:68:in
`installed_spec_directories'
from
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/source_index.rb:58:in
`from_installed_gems'
from
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:881:in
`source_index'
from
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/gem_path_searcher.rb:81:in
`init_gemspecs'
from
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/gem_path_searcher.rb:13:in
`initialize'
from
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:839:in
`new'
from
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:839:in
`searcher'
from
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:838:in
`synchronize'
from
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:838:in
`searcher'
from
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:478:in
`find_files'
from
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:1103
from /usr/bin/gem:8:in `require'
from /usr/bin/gem:8
$ cd learn_ruby/00_hello
$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb,
Rakefile.rb)
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2377:in
`raw_load_rakefile'
(See full trace by running task with --trace)

On Wed, Aug 7, 2013 at 6:45 PM, Isaac A. Murchie
notifications@github.comwrote:

> Hi! Sorry to hear you're having problems.
> 
> Where are you running "rake"? You should be inside one of the numbered
> directories (e.g., learn_ruby/00_hello/) when running it.
> 
> So:
> 
> cd learn_ruby/00_hello
> rake
> 
> Ought to work (your fork of the repository has the Rakefile in it, I can
> see).
> 
> Best,
> Isaac.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/alexch/learn_ruby/issues/12#issuecomment-22290125
> .

## 

_Best,_

*
*

_Jennifer Turner_

_Ph: 718.813.0625_

_Email: JenniferTurner202@gmail.com_

_This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
If you are not the named addressee you should not disseminate, distribute
or copy this e-mail. Please notify the sender immediately by e-mail if you
have received this e-mail by mistake and delete this e-mail from your
system. If you are not the intended recipient you are notified that
disclosing, copying, distributing or taking any action in reliance on the
contents of this information is strictly prohibited._

**Comment by imurchie** [comment]
Ooph! It looks like something is wrong in the Ruby installation. I would do a complete uninstall (google the steps. StackOverflow has some discussions... it will vary according to system to a small extent, most likely). The a new install of rvm or rbenv, and then Ruby. 

Sorry this is happening at such an early stage!

**Comment by JennTurnr** [comment]
Will do, and thank you again! 

Best,

Jennifer Turner
